### ISSUE TITLE
Running on asp.net api sln results in System.InvalidProjectFileException

### ISSUE THREAD

**Issue by trampster** [sensslen/nuget-license#12]
Running using the the arguments `nuget-license -i ApiServer.sln -t -d licenses` on our Asp.net web api project results in the following exception:

```
Unhandled exception. Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Could not find file '/home/daniel/Work/hydra-src/apps/API-Server/Pttox.Forms.sln'.  /home/daniel/Work/hydra-src/apps/API-Server/Pttox.Forms.sln
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()
   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)
   at NuGetUtility.Wrapper.MsBuildWrapper.MsBuildAbstraction.GetProjectsFromSolution(String inputPath) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Wrapper/MsBuildWrapper/MsBuildAbstraction.cs:line 57
   at NuGetUtility.ReferencedPackagesReader.ProjectsCollector.GetProjects(String inputPath) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/ReferencedPackagesReader/ProjectsCollector.cs:line 15
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+MoveNext() in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Extension/AsyncEnumerableExtension.cs:line 19
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/LicenseValidator/LicenseValidator.cs:line 33
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/LicenseValidator/LicenseValidator.cs:line 33
   at NuGetUtility.Program.OnExecuteAsync(CancellationToken cancellationToken) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 126
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at NuGetUtility.Program.Main(String[] args) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 86
   at NuGetUtility.Program.<Main>(String[] args)
Aborted (core dumped)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at NuGetUtility.Program.Main(String[] args) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 86
   at NuGetUtility.Program.<Main>(String[] args)
Aborted (core dumped)
```

The readme says that the -i is "Project or Solution to be analyzed" so I would expect it to handle a sln file.

**Comment by sensslen** [comment]
Can you provide a minimal reproduction example? The file is in fact detected to be a solution, however msbuild seems to have issues finding the file `/home/daniel/Work/hydra-src/apps/API-Server/Pttox.Forms.sln`. Can you verify the path is correct? To me it looks as if the path given should be relative (without the leading /) and is given in absolute form.

**Comment by trampster** [comment]
Turns out was a mistake in my usage, I was mixing up to projects and using the command for one on the other. I do still have an a crash with Unhandled exception. NuGetUtility.LicenseValidator.LicenseDownloadException: Failed to download license for package System.Buffers (4.3.0). But I'll raise that separately.
