### ISSUE TITLE
Unhandled Exception after adding NuGet.Config to solution

### ISSUE THREAD

**Issue by Kagemusha-san** [sensslen/nuget-license#41]
We have the following project structure for our .NET 8 project
```
| MyProject
|- src
   |- MyProject.Common (contains .csproj + source)
   |- MyProject.WebApi (contains .csproj + source)
   |- ...
|- MyProject.sln
|- NuGet.Config
```
and are building a docker image for the application. In the `Dockerfile` we install nuget-license and execute it to generate a list of licenses

```
FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build

WORKDIR /app

COPY ./src ./src
COPY MyProject.sln NuGet.Config ./

RUN dotnet restore "src/MyProject.WebApi/MyProject.WebApi.csproj"
RUN dotnet build "src/MyProject.WebApi/MyProject.WebApi.csproj" --no-restore -c Release -o out

RUN dotnet tool install --global nuget-license
# Only pass projects to nuget-license that do not start with Tests.
RUN tests=$(find src/*/*.csproj -name '*.csproj' ! -path "src/Tests.*/*.csproj" -exec echo -n '"{}", ' \;)  \
    && tests=${tests::-2} && echo "[${tests}]" > projects-filter.json \
    && nuget-license --json-input projects-filter.json > LICENSES.html

...
```

Everything was working fine until `NuGet.Config` file was added to the solution. Since then build fails with following exception
```
Unhandled exception. NuGet.Configuration.NuGetConfigurationException: Unexpected failure reading NuGet.Config. Path: '/app/src/MyProject.Common/MyProject.Common.csproj/NuGet.Config'.
 ---> System.IO.IOException: The file '/app/src/MyProject.Common/MyProject.Common.csproj' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at NuGet.Configuration.FileSystemUtility.AddFile(String fullPath, Action`1 writeToStream)
   at NuGet.Configuration.FileSystemUtility.GetOrCreateDocument(XDocument content, String fullPath)
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass23_0.<.ctor>b__0()
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Configuration.SettingsFile.ExecuteSynchronized(Action ioOperation)
   at NuGet.Configuration.SettingsFile..ctor(String directoryPath, String fileName, Boolean isMachineWide, Boolean isReadOnly)
   at NuGet.Configuration.Settings.ReadSettings(String settingsRoot, String settingsPath, Boolean isMachineWideSettings, Boolean isAdditionalUserWideConfig, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.<>c__DisplayClass29_0.<LoadSettings>b__0(String f)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root)
   at NuGetUtility.Program.GetPackageInfos(ProjectWithReferencedPackages projectWithReferences, IEnumerable`1 overridePackageInformation, CancellationToken cancellation) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 155
   at NuGetUtility.Program.<>c__DisplayClass35_0.<OnExecuteAsync>b__1(ProjectWithReferencedPackages p) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 132
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+MoveNext() in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Extension/AsyncEnumerableExtension.cs:line 21
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages, CancellationToken token) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/LicenseValidator/LicenseValidator.cs:line 35
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages, CancellationToken token) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/LicenseValidator/LicenseValidator.cs:line 35
   at NuGetUtility.Program.OnExecuteAsync(CancellationToken cancellationToken) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 133
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at NuGetUtility.Program.Main(String[] args) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 93
   at NuGetUtility.Program.<Main>(String[] args)
/bin/bash: line 1:    13 Aborted                 nuget-license --json-input projects-filter.json > LICENSES.html
```

I'm not sure what's going on here and why it tries to load `NuGet.Config` file from Common project folder altough it's only located in root folder (as it should be). Any ideas what could be the problem here?

**Comment by sensslen** [comment]
It's very hard to tell what is happening here. To be clear, the nuget.config file will be used by nuget-license as nuget-license relies on the microsoft nuget implementation to get all the information. Can you do the following:
- Test whether the issue still occurs if you do not run the steps in the docker container?
- Try create a minimal example with source code you can share so that I can have a look?

**Comment by Kagemusha-san** [comment]
Thanks for the quick response. I'm happy to help as much as I can 😸 

- Problem also appears when executing the tool on CLI and not in docker. 
- I created a [minimal example](https://github.com/Kagemusha-san/nuget-license-minimal). While testing things, I found out that it is connected to having a `NuGet.Config` file while providing a filter with `--json-input`.

**Comment by sensslen** [comment]
Thank you - I'll have a look when I get time. Feel free to debug and create a Pull Request....

**Comment by sensslen** [comment]
This is because one of the changes in that branch was to make sure all project paths are absolute. Please try the beta version published - it should resolve your issue…Von meinem iPhone gesendetAm 28.02.2024 um 10:21 schrieb Kagemusha-san ***@***.***>:﻿
I investigated the problem and it seems to be connected to how NuGet.Configuration.Settings determines the location of a NuGet.Config file. It boiled down to this part
var tuple = GetFileNameAndItsRoot(settingsRoot, settingsPath);
var filename = tuple.Item1; // NuGet.Config
var root = tuple.Item2; // C:/repositories/misc/nuget-license/src/NuGetUtility/bin/Debug/net8.0/src/WebApi/WebApi.csproj/NuGet.Config
return new SettingsFile(root, filename, isMachineWideSettings, isAdditionalUserWideConfig); // exception is thrown here
When providing an absolute path to project files (["C:/repositories/misc/nuget-license/src/NuGetUtility/bin/Debug/net8.0/src/WebApi/WebApi.csproj"] instead of ["src/WebApi/WebApi.csproj"]), everything works fine. Could also verify the behavior in our Dockerfile.
In main branch it works with both relative and absolute paths.

**Comment by Kagemusha-san** [comment]
As said in my last comment, it also works with the current release once providing absolute paths. I also tested on main branch and beta version in docker to verify the behavior of the latest version.
