### ISSUE TITLE
Error downloading license information

### ISSUE THREAD

**Issue by bent-rasmussen** [sensslen/nuget-license#64]
Downloading appears to stop once the tool tries to download license information from the `FSharp.Control.AsyncSeq` package:

```
D:\Foo\src>nuget-license --input Foo.sln --include-transitive -d .\license-information

Unhandled exception. NuGetUtility.LicenseValidator.LicenseDownloadException: Failed to download license for package FSharp.Control.AsyncSeq (3.2.1).
Context: D:\Foo\Foo\Foo\src\Foo\Foo.csproj
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGetUtility.Wrapper.HttpClientWrapper.FileDownloader.TryDownload(String fileName, Uri url, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\HttpClientWrapper\FileDownloader.cs:line 72
   at NuGetUtility.Wrapper.HttpClientWrapper.FileDownloader.TryDownload(String fileName, Uri url, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\HttpClientWrapper\FileDownloader.cs:line 76
   at NuGetUtility.Wrapper.HttpClientWrapper.FileDownloader.DownloadFile(Uri url, String fileName, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\HttpClientWrapper\FileDownloader.cs:line 29
   at NuGetUtility.LicenseValidator.LicenseValidator.ValidateLicenseByUrl(IPackageMetadata info, String context, ConcurrentDictionary`2 result, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\LicenseValidator\LicenseValidator.cs:line 180
   --- End of inner exception stack trace ---
   at NuGetUtility.LicenseValidator.LicenseValidator.ValidateLicenseByUrl(IPackageMetadata info, String context, ConcurrentDictionary`2 result, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\LicenseValidator\LicenseValidator.cs:line 190
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\LicenseValidator\LicenseValidator.cs:line 53
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\LicenseValidator\LicenseValidator.cs:line 39
   at NuGetUtility.Program.OnExecuteAsync(CancellationToken cancellationToken) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Program.cs:line 129
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at NuGetLicenseCore.Program.Main(String[] args) in D:\a\nuget-license\nuget-license\src\NuGetLicenseCore\Program.cs:line 14
   at NuGetLicenseCore.Program.<Main>(String[] args)
   
```

The solution uses central package management.

**Comment by sensslen** [comment]
This happens because the license URL returns a 404 error -- see attached image.
In this case you need to contact the publisher of that package and request a corrected package and in the mean time manually specify the license using the override possibility provided by `nuget-license`
![image](https://github.com/sensslen/nuget-license/assets/3428860/b354044c-2d01-46e3-8cbf-883d1c56c673)

**Comment by sensslen** [comment]
Closing as there is nothing we can do when the nuget package does not link an appropriate license

**Comment by bent-rasmussen** [comment]
I guess I was expecting an "report and continue" behavior but I see your point, in that you have another workaround :-)
