### ISSUE TITLE
Invalid Version String Handling with Pinned NuGet Package Versions

### ISSUE THREAD

**Issue by JvanderStad** [sensslen/nuget-license#77]
# Description
I am encountering an issue related to pinned NuGet package versions, which appears to be due to the lack of support for version ranges. According to the [NuGet documentation](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges), version ranges should be supported, but the error suggests otherwise.

# Error Details
```
System.ArgumentException: '[9.5.0]' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.Versioning.NuGetVersion..ctor(String version)
   at NuGetUtility.Wrapper.NuGetWrapper.Versioning.WrappedNuGetVersion..ctor(String version) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\NuGetWrapper\Versioning\WrappedNuGetVersion.cs:line 19
   at NuGetUtility.Wrapper.MsBuildWrapper.MsBuildAbstraction.<>c.<GetPackageReferencesFromProjectForFramework>b__5_1(ITaskItem p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\MsBuildWrapper\MsBuildAbstraction.cs:line 38
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.IsDirectlyReferenced(ILockFileLibrary library, IEnumerable`1 directlyReferencedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 91
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.<>c__DisplayClass7_0.<GetReferencedLibrariesForTarget>b__1(ILockFileLibrary l) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 82
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGetUtility.Extensions.HashSetExtension.AddRange[T](HashSet`1 source, IEnumerable`1 items) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Extensions\HashSetExtension.cs:line 18
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.TryGetInstalledPackagesFromAssetsFile(Boolean includeTransitive, IProject project, IEnumerable`1& installedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 61
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.GetInstalledPackages(String projectPath, Boolean includeTransitive) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 32
   at NuGetUtility.Program.<>c__DisplayClass37_0.<OnExecuteAsync>b__1(String p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Program.cs:line 126
System.ArgumentException: '[4.5.3.3]' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.Versioning.NuGetVersion..ctor(String version)
   at NuGetUtility.Wrapper.NuGetWrapper.Versioning.WrappedNuGetVersion..ctor(String version) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\NuGetWrapper\Versioning\WrappedNuGetVersion.cs:line 19
   at NuGetUtility.Wrapper.MsBuildWrapper.MsBuildAbstraction.<>c.<GetPackageReferencesFromProjectForFramework>b__5_1(ITaskItem p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\MsBuildWrapper\MsBuildAbstraction.cs:line 38
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.IsDirectlyReferenced(ILockFileLibrary library, IEnumerable`1 directlyReferencedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 91
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.<>c__DisplayClass7_0.<GetReferencedLibrariesForTarget>b__1(ILockFileLibrary l) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 82
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGetUtility.Extensions.HashSetExtension.AddRange[T](HashSet`1 source, IEnumerable`1 items) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Extensions\HashSetExtension.cs:line 18
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.TryGetInstalledPackagesFromAssetsFile(Boolean includeTransitive, IProject project, IEnumerable`1& installedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 61
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.GetInstalledPackages(String projectPath, Boolean includeTransitive) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 32
   at NuGetUtility.Program.<>c__DisplayClass37_0.<OnExecuteAsync>b__1(String p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Program.cs:line 126
```

**Comment by sensslen** [comment]
@JvanderStad thank you for reporting this issue. Are you able to provide a reproduction sample?

**Comment by sensslen** [comment]
@JvanderStad would you mind creating a small example that does trigger the error? With this I should be able to quickly resolve the issue. Currently I do not have enough information to find the issue, as nuget-license normally reads the projects lock file that is generated when restoring packages and that file contains the resolved versions rather than the version range syntax you describe....

**Comment by JvanderStad** [comment]
No worries, this `csproj` will fail

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[8.0.1]" />
  </ItemGroup>

</Project>
```

`& nuget-license -i .\ConsoleApp1.csproj`

```
System.ArgumentException: '[8.0.1]' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.Versioning.NuGetVersion..ctor(String version)
   at NuGetUtility.Wrapper.NuGetWrapper.Versioning.WrappedNuGetVersion..ctor(String version) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\NuGetWrapper\Versioning\WrappedNuGetVersion.cs:line 19
   at NuGetUtility.Wrapper.MsBuildWrapper.MsBuildAbstraction.<>c.<GetPackageReferencesFromProjectForFramework>b__5_1(ITaskItem p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\MsBuildWrapper\MsBuildAbstraction.cs:line 38
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.IsDirectlyReferenced(ILockFileLibrary library, IEnumerable`1 directlyReferencedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 91
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.<>c__DisplayClass7_0.<GetReferencedLibrariesForTarget>b__1(ILockFileLibrary l) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 82
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGetUtility.Extensions.HashSetExtension.AddRange[T](HashSet`1 source, IEnumerable`1 items) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Extensions\HashSetExtension.cs:line 18
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.TryGetInstalledPackagesFromAssetsFile(Boolean includeTransitive, IProject project, IEnumerable`1& installedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 61
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.GetInstalledPackages(String projectPath, Boolean includeTransitive) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 32
   at NuGetUtility.Program.<>c__DisplayClass37_0.<OnExecuteAsync>b__1(String p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Program.cs:line 126
```

**Comment by sensslen** [comment]
@JvanderStad I created #79 which should fix the issue reported. Thanks again for reporting and providing the steps to reproduce. Would you mind verifying that the problem is acutally fixed? Thanks!
