### ISSUE TITLE
Exception when use -override

### ISSUE THREAD

**Issue by Maniues** [sensslen/nuget-license#78]
I got the following errors when I used -override option with JSON file:
```
$ nuget-license -i PROJECT.sln -ignore Licensing.IgnoredPackages.json -o jsonPretty --override-package-information Licensing.Repaired.json > ThirdPartyNotices.json
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGetUtility.PackageInformationReader.PackageInformationReader.<>c__DisplayClass7_0.<TryGetPackageInfoFromCustomInformation>b__0(CustomPackageInformation info) in D:\a\nuget-license\nuget-license\src\NuGetUtility\PackageInformationReader\PackageInformationReader.cs:line 92
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGetUtility.PackageInformationReader.PackageInformationReader.TryGetPackageInfoFromCustomInformation(PackageIdentity package) in D:\a\nuget-license\nuget-license\src\NuGetUtility\PackageInformationReader\PackageInformationReader.cs:line 91
   at NuGetUtility.PackageInformationReader.PackageInformationReader.GetPackageInfo(ProjectWithReferencedPackages projectWithReferencedPackages, CancellationToken cancellation)+MoveNext() in D:\a\nuget-license\nuget-license\src\NuGetUtility\PackageInformationReader\PackageInformationReader.cs:line 33
   at NuGetUtility.PackageInformationReader.PackageInformationReader.GetPackageInfo(ProjectWithReferencedPackages projectWithReferencedPackages, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+MoveNext() in D:\a\nuget-license\nuget-license\src\NuGetUtility\Extension\AsyncEnumerableExtension.cs:line 24
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+MoveNext() in D:\a\nuget-license\nuget-license\src\NuGetUtility\Extension\AsyncEnumerableExtension.cs:line 24
   at NuGetUtility.Extension.AsyncEnumerableExtension.SelectMany[TSource,TResult](IEnumerable`1 input, Func`2 transform)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\LicenseValidator\LicenseValidator.cs:line 39
   at NuGetUtility.LicenseValidator.LicenseValidator.Validate(IAsyncEnumerable`1 packages, CancellationToken token) in D:\a\nuget-license\nuget-license\src\NuGetUtility\LicenseValidator\LicenseValidator.cs:line 39
   at NuGetUtility.Program.OnExecuteAsync(CancellationToken cancellationToken) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Program.cs:line 136
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at NuGetLicenseCore.Program.Main(String[] args) in D:\a\nuget-license\nuget-license\src\NuGetLicenseCore\Program.cs:line 14
   at NuGetLicenseCore.Program.<Main>(String[] args)
```

**Comment by sensslen** [comment]
Can you provide a sample project to reproduce the error?

**Comment by sensslen** [comment]
I will take a look, thank you.
