### ISSUE TITLE
Project file could not be loaded/Failed to get the project assets file

### ISSUE THREAD

**Issue by SimonMeysman** [sensslen/nuget-license#93]
I have nuget-license version `3.0.13` installed with dotnet `8.0.302`. When running this tool either locally on windows, on ubuntu vm or on a ubuntu-latest github action runner, I get the following error when passing a folder as input:

```
Run nuget-license -t -i Server/ -o jsonPretty > Server/licenses.json
  nuget-license -t -i Server/ -o jsonPretty > Server/licenses.json
  cat Server/licenses.json
  shell: /usr/bin/bash -e {0}
Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Access to the path '/home/runner/work/MyProject/MyRepo/Server/' is denied.  /home/runner/work/MyProject/MyRepo/Server/
 ---> System.UnauthorizedAccessException: Access to the path '/home/runner/work/MyProject/MyRepo/Server/' is denied.
 ---> System.IO.IOException: Permission denied
```

When I pass the solution file instead, it correctly identifies the list of all the .csproj files, but gives for every one of these projects the following error:

```
Run nuget-license -t -i Server/MySolution.sln -o jsonPretty > Server/licenses.json
  nuget-license -t -i Server/ -o jsonPretty > Server/licenses.json
  cat Server/licenses.json
  shell: /usr/bin/bash -e {0}

NuGetUtility.Wrapper.MsBuildWrapper.MsBuildAbstractionException: Failed to get the project assets file for project /home/runner/work/MyProject/MyRepo/Server/ConsoleTestApp/ConsoleTestApp.csproj (/home/runner/work/MyProject/MyRepo/Server/ConsoleTestApp/obj/project.assets.json)
   at NuGetUtility.Wrapper.MsBuildWrapper.ProjectWrapper.TryGetAssetsPath(String& assetsFile) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Wrapper\MsBuildWrapper\ProjectWrapper.cs:line 30
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.TryLoadAssetsFile(IProject project, ILockFile& assetsFile) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 115
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.TryGetInstalledPackagesFromAssetsFile(Boolean includeTransitive, IProject project, String targetFramework, IEnumerable`1& installedPackages) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 51
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.GetInstalledPackages(String projectPath, Boolean includeTransitive, String targetFramework) in D:\a\nuget-license\nuget-license\src\NuGetUtility\ReferencedPackagesReader\ReferencedPackageReader.cs:line 32
   at NuGetUtility.Program.<>c__DisplayClass40_0.<OnExecuteAsync>b__1(String p) in D:\a\nuget-license\nuget-license\src\NuGetUtility\Program.cs:line 131
```

Removing the other parameters (except the input) does not change the result.

**Comment by sensslen** [comment]
Did you restore nuget packages before running nuget-license? Can you provide a minimal reproduction example I can have a look at? The first error happens because nuget-license does not support a folder as input. Either you provide a solution, a project or a json file containing the paths to all projects to be analyzed....

**Comment by SimonMeysman** [comment]
Solved! I was running it on a clean checkout without restoring. I thought I read in the documentation that folders were supported, but after a second look, it seems like that was entirely wrong. Thank you for the swift reply and great software!
